In [1]:
import os
from typing import List, Dict
from dotenv import load_dotenv

from langfuse import Langfuse
import pandas as pd
import tiktoken

from config.base_config import rag_config

In [2]:
load_dotenv()

LANGFUSE_SECRET_KEY = os.environ.get("LANGFUSE_SECRET_KEY", None)
LANGFUSE_PUBLIC_KEY = os.environ.get("LANGFUSE_PUBLIC_KEY", None)
LANGFUSE_HOST = "http://localhost:3000"

In [3]:
langfuse = Langfuse(
  secret_key=LANGFUSE_SECRET_KEY,
  public_key=LANGFUSE_PUBLIC_KEY,
  host=LANGFUSE_HOST
)

In [4]:
tokenizer = tiktoken.get_encoding("o200k_base")

In [5]:
pricing = {
    "gpt-4o": {
        "input": 5,
        "output": 15
    },
    "gpt-4o-2024-08-06": {
        "input": 2.5,
        "output": 10
    },
    "gpt-4o-2024-05-13": {
        "input": 5,
        "output": 15
    },
    "gpt-4o-mini": {
        "input": 0.15,
        "output": 0.6
    },
    "gpt-4o-mini-2024-07-18": {
        "input": 0.15,
        "output": 0.6
    },
    "chatgpt-4o-latest": {
        "input": 5.00,
        "output": 15.00
    },
    "gpt-4-turbo": {
        "input": 10.00,
        "output": 30.00
    },
    "gpt-4-turbo-2024-04-09": {
        "input": 10.00,
        "output": 30.00
    },
    "gpt-4": {
        "input": 30.00,
        "output": 60.00
    },
    "gpt-4-32k": {
        "input": 60.00,
        "output": 120.00
    },
    "gpt-4-0125-preview": {
        "input": 10.00,
        "output": 30.00
    },
    "gpt-4-1106-preview": {
        "input": 10.00,
        "output": 30.00
    },
    "gpt-4-vision-preview": {
        "input": 10.00,
        "output": 30.00
    },
    "gpt-3.5-turbo-0125": {
        "input": 0.50,
        "output": 1.50
    },
    "gpt-3.5-turbo-instruct": {
        "input": 1.50,
        "output": 2.00
    },
    "gpt-3.5-turbo-1106": {
        "input": 1.00,
        "output": 2.00
    },
    "gpt-3.5-turbo-0613": {
        "input": 1.50,
        "output": 2.00
    },
    "gpt-3.5-turbo-16k-0613": {
        "input": 3.00,
        "output": 4.00
    },
    "gpt-3.5-turbo-0301": {
        "input": 1.50,
        "output": 2.00
    }
 }

In [6]:
model = rag_config["llm"]["model"]

if model in ["gpt-4o", "gpt-4o-2024-05-13", "gpt-4o-2024-08-06", "chatgpt-4o-latest", "gpt-4o-mini", "gpt-4o-mini-2024-07-18"]:
    encoding = "o200k_base"
elif model in ["gpt-4-turbo", "gpt-4-turbo-2024-04-09", "gpt-4-turbo-preview", "gpt-4-0125-preview", "gpt-4-1106-preview", "gpt-4",
               "gpt-4-0613", "gpt-4-0314", "gpt-3.5-turbo-0125", "gpt-3.5-turbo", "gpt-3.5-turbo-1106", "gpt-3.5-turbo-instruct"]:
    encoding = "cl100k_base"

tokenizer = tiktoken.get_encoding(encoding)

def get_cost(tokenizer, input: List[str], output: List[str], pricing: Dict, model: str):

    n_input_toks = len(tokenizer.encode(input))
    n_output_toks = len(tokenizer.encode(output))
    input_cost = n_input_toks * pricing[model]["input"] / 1_000_000
    output_cost = n_input_toks * pricing[model]["output"] / 1_000_000

    return input_cost + output_cost

### Get traces

In [7]:
traces = langfuse.fetch_traces().data

In [8]:
trace_data = []

for i, trace in enumerate(traces):
    input = trace.input["args"][1]["query"]
    if trace.output:
        if all(isinstance(item, str) for item in trace.output):
            output = "".join(trace.output)
    else:
        output = ""
    trace_data.append(
        {
            "id": trace.id,
            "timestamp": trace.timestamp.strftime('%Y-%m-%d %H:%M:%S'),
            "latency": trace.latency,
            "cost": get_cost(tokenizer=tokenizer,
                       input=input,
                       output=output,
                       pricing=pricing,
                       model=model),
            "input": input,
            "output": output
        }
    )

trace_data_df = pd.DataFrame(trace_data)
trace_data_df

,id,timestamp,latency,cost,input,output
0,2ceaf809-f0f8-4ea2-bbb1-a8e945cd0fdb,2024-08-27 15:08:16,9.156,0.00028,Que signifie concrètement «adaptation au pouv...,### Adaptation au pouvoir d’achat\n\nL'adaptat...
1,9552ce61-beda-4a45-80a1-55f80897c5c1,2024-08-26 14:33:18,13.052,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...
2,df7d6afa-0b89-44a7-9824-51ea9a29df24,2024-08-26 14:32:28,12.679,0.00022,Welche Arten von Familienzulagen werden ausger...,
3,2c2cfcaa-a793-431c-a471-bc5a2aa9130f,2024-08-26 14:31:28,13.228,0.00022,Welche Arten von Familienzulagen werden ausger...,
4,49dc7fb8-8adc-4f57-973f-81a9171e4812,2024-08-26 14:29:55,12.930,0.00022,Welche Arten von Familienzulagen werden ausger...,
5,c8235a35-c48d-4c48-9b4a-662dc6b49a28,2024-08-26 14:29:06,12.644,0.00022,Welche Arten von Familienzulagen werden ausger...,\n\n<a href='https://www.eak.admin.ch/eak/de/h...
6,0a0d86a6-97ca-4239-a979-bc4f09b9d416,2024-08-26 14:28:57,2.519,0.00020,decoded_line = line.decode('utf-8'),\n\n<a href='https://www.eak.admin.ch/eak/de/h...
7,22e6eb04-2354-4a97-abdd-b0ccc42460eb,2024-08-26 14:27:45,13.083,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...
8,89a1ba1b-99e4-4702-96a6-4c8ffc326121,2024-08-26 14:24:46,13.180,0.00022,Welche Arten von Familienzulagen werden ausger...,
9,aad43851-4efb-4219-9c69-34daef131c17,2024-08-26 14:23:06,13.082,0.00022,Welche Arten von Familienzulagen werden ausger...,
10,dab0259c-d900-43cf-b350-d01229bb1e4b,2024-08-26 14:21:59,12.861,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...
11,0737570e-5406-4001-9ab8-bc251f6f71c4,2024-08-26 14:13:59,13.012,0.00022,Welche Arten von Familienzulagen werden ausger...,
12,dabfae08-0cb4-4197-9d57-b82196a23c3c,2024-08-26 14:12:39,12.939,0.00022,Welche Arten von Familienzulagen werden ausger...,\n\n<a href='https://www.eak.admin.ch/eak/de/h...
13,96ec992a-3289-4688-944d-a6c8139914e0,2024-08-26 14:11:39,4.594,0.00004,avs21,
14,0bc70af6-59e6-41d0-99eb-58ec24424833,2024-08-26 14:10:00,25.273,0.00010,was ist avs21,AVS21 (AHV-Reform 21) ist eine wichtige Reform...
15,983778a5-3a18-47f5-bf2c-d12813642c8f,2024-08-26 14:09:37,13.331,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...
16,ebbe1dc4-95ec-4d4f-ad0d-ba43bebb2a8b,2024-08-26 14:05:11,18.324,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""..."
17,9658990e-9dad-4e57-b9d5-aee8ec941197,2024-08-26 14:03:31,20.143,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""..."
18,a702f7eb-8063-48b1-bf2e-8cfbbfb339fd,2024-08-26 14:01:22,18.148,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""..."
19,10a05b30-d70f-4cf1-b808-3e1373b10de9,2024-08-26 13:52:04,18.714,0.00022,Welche Arten von Familienzulagen werden ausger...,of the state in the economyrole of the state ...
20,e57cfb74-fc4e-4795-aba9-8adab34c7e22,2024-08-26 13:48:42,18.686,0.00022,Welche Arten von Familienzulagen werden ausger...,of the state in the economyrole of the state ...
21,7fd3e25f-e6d4-48b0-8aa5-a4a2ba54ac6d,2024-08-26 13:46:43,18.544,0.00022,Welche Arten von Familienzulagen werden ausger...,of the state in the economyrole of the state ...
22,e96dde74-6228-4c34-a2b3-438ffc9c79c3,2024-08-26 13:46:08,18.903,0.00010,explain avs21,of the state in the economyrole of the state ...
23,6f691f4f-328c-42b9-802e-d3d3af112356,2024-08-26 13:28:14,18.745,0.00022,Welche Arten von Familienzulagen werden ausger...,
24,ad184e7d-3a30-4c54-b93d-7e85e441d655,2024-08-26 13:11:57,27.711,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""..."
25,07b3218f-436a-4760-bcd0-29319e7dde7e,2024-08-26 13:10:52,27.871,0.00006,avs21$,"= input(""What role do you have? "")if role == ""..."
26,cb4c2e9d-e7a1-4c12-b3d0-6e3e0a90713d,2024-08-26 13:08:32,27.901,0.00004,avs21,
27,69eeb12c-f90a-4785-9237-ed43df3ee433,2024-08-26 13:06:06,28.150,0.00004,avs21,
28,0bc7863c-c1c9-4f1b-8e30-91221c3c25b6,2024-08-26 13:04:14,25.908,0.00002,acs,
29,7728a4cd-4e65-4961-b58c-0b3bcab45f03,2024-08-26 12:59:44,28.523,0.00004,avs21,
30,ae89fe8f-fff4-4438-9c47-5bd458887ba2,2024-08-26 12:57:49,27.843,0.00004,avs21,
31,1f8f3a76-1293-4dfe-b618-f1b757e5a62a,2024-08-26 12:53:43,25.881,0.00004,avs21,
32,1bca5fde-8dfe-4db5-b488-e64cb3db74fe,2024-08-26 12:52:50,10.668,0.00004,avs21,
33,9aeb11b1-f083-4207-a7ad-c80d3f9657b0,2024-08-26 12:51:57,10.356,0.00004,avs21,
34,d4f3c362-857a-41cc-ba92-209d856c7bbe,2024-08-26 12:51:51,0.000,0.00002,string,
35,9aa9d1a5-f600-4407-8ee0-08f5dd83ae42,2024-08-26 12:26:57,0.000,0.00002,string,
36,c86c5553-7b91-46bd-a798-e32b2d36666a,2024-08-26 12:24:28,0.000,0.00002,string,
37,eaf00841-610e-4d6c-a0f3-4e4e773ddd28,2024-08-26 12:18:16,0.000,0.00002,string,
38,4aa2f704-bfc2-467b-b3ca-06f47da98698,2024-08-26 12:15:48,0.000,0.00002,string,
39,e9c7d1ae-6952-47ce-9f79-7a3374a9e9fe,2024-08-26 12:14:02,0.000,0.00002,string,
40,a258e0a2-b4e1-41e8-980c-34e7902fd364,2024-08-26 12:09:28,0.000,0.00002,string,
41,3048174e-fb20-4542-90c3-7e01e633265c,2024-08-26 11:44:36,10.007,0.00004,avs21,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
42,85869a1d-7a26-4b8d-9ff3-9171f8438107,2024-08-26 11:21:38,7.464,0.00004,avs21,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
43,72e31cee-fc70-44b1-bca3-8c44af4ce156,2024-08-26 11:21:28,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
44,adc8f2bb-0f2d-49a8-8953-dd9630be008a,2024-08-26 11:21:21,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
45,8d5335fd-fd94-49d7-b360-16a10fe58c10,2024-08-26 11:21:10,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
46,261be93a-7094-488f-8e4f-9e5fa7077b94,2024-08-26 11:20:04,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
47,5f8df965-cdc0-45f1-9136-ec707a72fdcd,2024-08-26 11:19:58,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
48,4d64df6a-e31b-45be-bb6b-b0e63b3a2c24,2024-08-26 11:19:52,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."
49,2693d086-bbaa-4365-945e-492a7b774ea9,2024-08-26 11:19:41,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr..."

In [9]:
trace_data_df.cost.sum()

0.0058400000000000014

In [10]:
trace_data_df.describe()

         latency       cost
count  50.000000  50.000000
mean   12.121060   0.000117
std     9.771015   0.000096
min     0.000000   0.000020
25%     0.000000   0.000020
50%    12.934500   0.000050
75%    18.707000   0.000220
max    28.523000   0.000280

### Observations

In [11]:
observations = langfuse.fetch_observations(name="retrieve")

In [12]:
obs = {obs.trace_id: obs.output for obs in observations.data}
trace_data_df["retrieval"] = trace_data_df["id"].map(obs)

In [13]:
trace_data_df

,id,timestamp,latency,cost,input,output,retrieval
0,2ceaf809-f0f8-4ea2-bbb1-a8e945cd0fdb,2024-08-27 15:08:16,9.156,0.00028,Que signifie concrètement «adaptation au pouv...,### Adaptation au pouvoir d’achat\n\nL'adaptat...,"[{'id': 284, 'tag': 'Familienzulagen', 'url': ..."
1,9552ce61-beda-4a45-80a1-55f80897c5c1,2024-08-26 14:33:18,13.052,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
2,df7d6afa-0b89-44a7-9824-51ea9a29df24,2024-08-26 14:32:28,12.679,0.00022,Welche Arten von Familienzulagen werden ausger...,,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
3,2c2cfcaa-a793-431c-a471-bc5a2aa9130f,2024-08-26 14:31:28,13.228,0.00022,Welche Arten von Familienzulagen werden ausger...,,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
4,49dc7fb8-8adc-4f57-973f-81a9171e4812,2024-08-26 14:29:55,12.930,0.00022,Welche Arten von Familienzulagen werden ausger...,,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
5,c8235a35-c48d-4c48-9b4a-662dc6b49a28,2024-08-26 14:29:06,12.644,0.00022,Welche Arten von Familienzulagen werden ausger...,\n\n<a href='https://www.eak.admin.ch/eak/de/h...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
6,0a0d86a6-97ca-4239-a979-bc4f09b9d416,2024-08-26 14:28:57,2.519,0.00020,decoded_line = line.decode('utf-8'),\n\n<a href='https://www.eak.admin.ch/eak/de/h...,"[{'id': 83, 'tag': None, 'url': 'https://www.e..."
7,22e6eb04-2354-4a97-abdd-b0ccc42460eb,2024-08-26 14:27:45,13.083,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
8,89a1ba1b-99e4-4702-96a6-4c8ffc326121,2024-08-26 14:24:46,13.180,0.00022,Welche Arten von Familienzulagen werden ausger...,,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
9,aad43851-4efb-4219-9c69-34daef131c17,2024-08-26 14:23:06,13.082,0.00022,Welche Arten von Familienzulagen werden ausger...,,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
10,dab0259c-d900-43cf-b350-d01229bb1e4b,2024-08-26 14:21:59,12.861,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
11,0737570e-5406-4001-9ab8-bc251f6f71c4,2024-08-26 14:13:59,13.012,0.00022,Welche Arten von Familienzulagen werden ausger...,,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
12,dabfae08-0cb4-4197-9d57-b82196a23c3c,2024-08-26 14:12:39,12.939,0.00022,Welche Arten von Familienzulagen werden ausger...,\n\n<a href='https://www.eak.admin.ch/eak/de/h...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
13,96ec992a-3289-4688-944d-a6c8139914e0,2024-08-26 14:11:39,4.594,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
14,0bc70af6-59e6-41d0-99eb-58ec24424833,2024-08-26 14:10:00,25.273,0.00010,was ist avs21,AVS21 (AHV-Reform 21) ist eine wichtige Reform...,"[{'id': 203, 'tag': None, 'url': 'https://www...."
15,983778a5-3a18-47f5-bf2c-d12813642c8f,2024-08-26 14:09:37,13.331,0.00022,Welche Arten von Familienzulagen werden ausger...,A: Welche Arten von Familienzulagen werden aus...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
16,ebbe1dc4-95ec-4d4f-ad0d-ba43bebb2a8b,2024-08-26 14:05:11,18.324,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""...","[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
17,9658990e-9dad-4e57-b9d5-aee8ec941197,2024-08-26 14:03:31,20.143,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""...","[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
18,a702f7eb-8063-48b1-bf2e-8cfbbfb339fd,2024-08-26 14:01:22,18.148,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""...","[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
19,10a05b30-d70f-4cf1-b808-3e1373b10de9,2024-08-26 13:52:04,18.714,0.00022,Welche Arten von Familienzulagen werden ausger...,of the state in the economyrole of the state ...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
20,e57cfb74-fc4e-4795-aba9-8adab34c7e22,2024-08-26 13:48:42,18.686,0.00022,Welche Arten von Familienzulagen werden ausger...,of the state in the economyrole of the state ...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
21,7fd3e25f-e6d4-48b0-8aa5-a4a2ba54ac6d,2024-08-26 13:46:43,18.544,0.00022,Welche Arten von Familienzulagen werden ausger...,of the state in the economyrole of the state ...,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
22,e96dde74-6228-4c34-a2b3-438ffc9c79c3,2024-08-26 13:46:08,18.903,0.00010,explain avs21,of the state in the economyrole of the state ...,"[{'id': 203, 'tag': None, 'url': 'https://www...."
23,6f691f4f-328c-42b9-802e-d3d3af112356,2024-08-26 13:28:14,18.745,0.00022,Welche Arten von Familienzulagen werden ausger...,,"[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
24,ad184e7d-3a30-4c54-b93d-7e85e441d655,2024-08-26 13:11:57,27.711,0.00022,Welche Arten von Familienzulagen werden ausger...,"= input(""What role do you have? "")if role == ""...","[{'id': 139, 'tag': 'Familienzulagen', 'url': ..."
25,07b3218f-436a-4760-bcd0-29319e7dde7e,2024-08-26 13:10:52,27.871,0.00006,avs21$,"= input(""What role do you have? "")if role == ""...","[{'id': 72, 'tag': None, 'url': 'https://ahv-i..."
26,cb4c2e9d-e7a1-4c12-b3d0-6e3e0a90713d,2024-08-26 13:08:32,27.901,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
27,69eeb12c-f90a-4785-9237-ed43df3ee433,2024-08-26 13:06:06,28.150,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
28,0bc7863c-c1c9-4f1b-8e30-91221c3c25b6,2024-08-26 13:04:14,25.908,0.00002,acs,,"[{'id': 196, 'tag': None, 'url': 'https://www...."
29,7728a4cd-4e65-4961-b58c-0b3bcab45f03,2024-08-26 12:59:44,28.523,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
30,ae89fe8f-fff4-4438-9c47-5bd458887ba2,2024-08-26 12:57:49,27.843,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
31,1f8f3a76-1293-4dfe-b618-f1b757e5a62a,2024-08-26 12:53:43,25.881,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
32,1bca5fde-8dfe-4db5-b488-e64cb3db74fe,2024-08-26 12:52:50,10.668,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
33,9aeb11b1-f083-4207-a7ad-c80d3f9657b0,2024-08-26 12:51:57,10.356,0.00004,avs21,,"[{'id': 65, 'tag': None, 'url': 'https://ahv-i..."
34,d4f3c362-857a-41cc-ba92-209d856c7bbe,2024-08-26 12:51:51,0.000,0.00002,string,,NaN
35,9aa9d1a5-f600-4407-8ee0-08f5dd83ae42,2024-08-26 12:26:57,0.000,0.00002,string,,NaN
36,c86c5553-7b91-46bd-a798-e32b2d36666a,2024-08-26 12:24:28,0.000,0.00002,string,,NaN
37,eaf00841-610e-4d6c-a0f3-4e4e773ddd28,2024-08-26 12:18:16,0.000,0.00002,string,,NaN
38,4aa2f704-bfc2-467b-b3ca-06f47da98698,2024-08-26 12:15:48,0.000,0.00002,string,,NaN
39,e9c7d1ae-6952-47ce-9f79-7a3374a9e9fe,2024-08-26 12:14:02,0.000,0.00002,string,,NaN
40,a258e0a2-b4e1-41e8-980c-34e7902fd364,2024-08-26 12:09:28,0.000,0.00002,string,,NaN
41,3048174e-fb20-4542-90c3-7e01e633265c,2024-08-26 11:44:36,10.007,0.00004,avs21,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...","[{'id': 30, 'tag': None, 'url': 'https://ahv-i..."
42,85869a1d-7a26-4b8d-9ff3-9171f8438107,2024-08-26 11:21:38,7.464,0.00004,avs21,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...","[{'id': 30, 'tag': None, 'url': 'https://ahv-i..."
43,72e31cee-fc70-44b1-bca3-8c44af4ce156,2024-08-26 11:21:28,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...",NaN
44,adc8f2bb-0f2d-49a8-8953-dd9630be008a,2024-08-26 11:21:21,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...",NaN
45,8d5335fd-fd94-49d7-b360-16a10fe58c10,2024-08-26 11:21:10,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...",NaN
46,261be93a-7094-488f-8e4f-9e5fa7077b94,2024-08-26 11:20:04,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...",NaN
47,5f8df965-cdc0-45f1-9136-ec707a72fdcd,2024-08-26 11:19:58,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...",NaN
48,4d64df6a-e31b-45be-bb6b-b0e63b3a2c24,2024-08-26 11:19:52,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...",NaN
49,2693d086-bbaa-4365-945e-492a7b774ea9,2024-08-26 11:19:41,0.000,0.00002,string,"Die Reform AHV 21, die am 1. Januar 2024 in Kr...",NaN

# Retrieval EVAL

In [65]:
import logging
logger = logging.getLogger()
logger.setLevel(logging.CRITICAL)

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from rag.rag_processor import processor
from config.base_config import rag_config
from database.models import Document

import pandas as pd

In [15]:
rag_config

{'enabled': True,
 'embedding': {'model': 'text-embedding-ada-002'},
 'retrieval': {'retrieval_method': ['top_k_retriever', 'reranking'],
  'top_k_retriever_params': {'top_k': 100},
  'bm25_retriever_params': {'k': 1.2, 'b': 0.75, 'top_k': 10},
  'query_rewriting_retriever_params': {'n_alt_queries': 3, 'top_k': 10},
  'contextual_compression_retriever_params': {'top_k': 4},
  'rag_fusion_retriever_params': {'n_alt_queries': 3, 'rrf_k': 60, 'top_k': 3},
  'reranking_params': {'model': 'rerank-multilingual-v3.0', 'top_k': 5},
  'routing': {'model': 'openai'},
  'top_k': 5,
  'metric': 'cosine_similarity'},
 'source_isolation': False,
 'llm': {'model': 'gpt-4o',
  'temperature': 0,
  'max_output_tokens': 2048,
  'top_p': 0.95,
  'stream': True}}

In [16]:
POSTGRES_USER = os.environ.get("POSTGRES_USER", None)
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", None)
POSTGRES_PORT = os.environ.get("POSTGRES_PORT", None)
POSTGRES_DB = os.environ.get("POSTGRES_DB", None)

def get_db():
    
    DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@localhost:{POSTGRES_PORT}/{POSTGRES_DB}"
    
    engine = create_engine(DATABASE_URL)
    
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    
    db = SessionLocal()

    return db

In [66]:
db = get_db()

### Choose dataset

In [ ]:
eval_data = pd.read_csv("indexing/data/eak_eval_fz.csv")
eval_data.tail()

In [ ]:
eval_data = pd.read_csv("indexing/data/memento_eval_qa_fz.csv")
eval_data.tail()

In [18]:
eval_data = pd.read_csv("indexing/data/memento_eval_qa_allgemeines.csv")
eval_data.tail()

,url,created_at,modified_at,question,answer,topic,subtopic,contains_table
42,https://www.ahv-iv.ch/p/1.07.f,NaN,NaN,A qui la bonification pour tâches éducatives e...,"Si, au moment du calcul de la rente, on ne dis...",Bonifications pour tâches éducatives,Parents divorcés ou pas mariés ensemble,False
43,https://www.ahv-iv.ch/p/1.07.f,NaN,NaN,Les bonifications pour tâches éducatives sont-...,Non. Si une personne a plusieurs enfants (égal...,Bonifications pour tâches éducatives,Effet de la bonification pour tâches éducatives,False
44,https://www.ahv-iv.ch/p/1.07.f,NaN,NaN,Comment les bonifications pour tâches éducativ...,"En principe, il est toujours tenu compte d’ann...",Bonifications pour tâches éducatives,Effet de la bonification pour tâches éducatives,False
45,https://www.ahv-iv.ch/p/1.07.f,NaN,NaN,A quel montant s’élèvent les bonifications pou...,Le montant de la bonification pour tâches éduc...,Bonifications pour tâches éducatives,Effet de la bonification pour tâches éducatives,False
46,https://www.ahv-iv.ch/p/1.07.f,NaN,NaN,La caisse de compensation doit-elle être infor...,"Non. Ce n’est pas à la naissance d’un enfant, ...",Bonifications pour tâches éducatives,Marche à suivre lors d’une modification de l’é...,False

### Evaluation params

In [19]:
language = None
tag = None
k = 100
#processor.retriever_client.reranker = None
processor.retriever_client.reranker.top_k = 10

### Evaluate

In [20]:
docs = []
for i, row in eval_data.iterrows():
    docs.append(processor.retriever_client.get_documents(db, row.question, language=language, tag=tag, k=k))

2024-08-27 18:16:49,516 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:16:52,089 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:16:52,561 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:16:54,287 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:16:54,807 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:16:56,457 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:16:56,895 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:16:58,426 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:16:58,907 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:00,986 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:01,441 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:03,852 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:04,333 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:06,766 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:07,163 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:09,485 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:09,913 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:12,455 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:12,824 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:14,503 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:14,981 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:17,063 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:17,514 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:19,418 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:19,821 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:21,670 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:22,113 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:24,363 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:24,799 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:27,238 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:27,685 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:30,169 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:30,625 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:32,859 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:33,208 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:35,291 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:35,852 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:37,647 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:37,998 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:40,549 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:40,943 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:43,480 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:43,942 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:46,142 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:46,533 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:48,368 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:48,786 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:51,368 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:51,754 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:54,234 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:54,660 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:56,720 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:17:57,216 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:17:59,458 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:00,000 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:02,151 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:02,682 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:04,886 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:05,467 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:07,849 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:08,257 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:10,246 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:10,775 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:12,466 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:12,935 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:15,047 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:15,504 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:17,274 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:17,730 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:20,272 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:20,674 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:22,392 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:22,809 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:24,544 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:24,981 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:26,903 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:27,314 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:29,457 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:30,013 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:32,123 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:32,571 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:34,990 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:35,470 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:37,549 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:38,143 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:40,414 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:40,971 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:42,771 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:43,313 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:45,361 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:45,784 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:48,300 - rag.retriever.reranker - INFO - Finished reranking 10 documents.
2024-08-27 18:18:48,682 - rag.retriever.reranker - INFO - Reranking 100 documents...
2024-08-27 18:18:50,536 - rag.retriever.reranker - INFO - Finished reranking 10 documents.

In [21]:
retrieved_docs = []
for doc in docs:
    list_docs = []
    for d in doc:
        list_docs.append(d["url"])
    retrieved_docs.append(list_docs)

eval_data["retrieval"] = retrieved_docs

In [27]:
# recall@k
k = 3
#for k in [100, 10, 5, 3, 2, 1]:
recall = eval_data.apply(lambda row: row['url'].replace("www.", "") in [url.replace("www.", "") for url in row['retrieval']][:k], axis=1)
print(k, ": ", recall.sum() / len(recall))

3 :  0.7659574468085106

In [38]:
for i, row in eval_data[~recall][["question", "url", "retrieval"]].iterrows():
    print(row.question)
    print(row.url)
    print(row.retrieval)
    print("--------------------_")

Qu’entend-on par mois de cotisation ?
https://www.ahv-iv.ch/p/1.04.f
['https://ahv-iv.ch/p/2.05.f', 'https://ahv-iv.ch/p/2.03.f', 'https://ahv-iv.ch/p/2.04.f', 'https://ahv-iv.ch/p/4.07.f', 'https://ahv-iv.ch/p/2.06.f', 'https://ahv-iv.ch/p/2.02.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/kontoauszug.html', 'https://ahv-iv.ch/p/2.08.f', 'https://ahv-iv.ch/p/6.08.f', 'https://eak.admin.ch/eak/fr/home/Firmen/familienzulagen/grundlagen.html']
--------------------_
Où les revenus sont-ils inscrits ?
https://www.ahv-iv.ch/p/1.04.f
['https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/kontoauszug.html', 'https://ahv-iv.ch/p/1.05.f', 'https://ahv-iv.ch/p/1.01.f', 'https://eak.admin.ch/eak/fr/home/Firmen/Personal/versicherungsausweis.html', 'https://ahv-iv.ch/p/1.02.f', 'https://eak.admin.ch/eak/fr/home/EAK/publikationen/jahresberichte/jahresbericht-2023/beitraege.html', 'https://eak.admin.ch/eak/fr/home/EAK/unsere-leistungen.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand/heirat_eingetragene_partnerschaft.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/steuerausweis.html', 'https://ahv-iv.ch/p/5.01.f']
--------------------_
Quel revenu est inscrit pour les personnes sans activité lucrative ?
https://www.ahv-iv.ch/p/1.04.f
['https://ahv-iv.ch/p/2.03.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/kontoauszug.html', 'https://ahv-iv.ch/p/1.01.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/arbeitsunterbruch_keine_erwerbstaetigkeit/keine_erwerbstaetigkeit.html', 'https://ahv-iv.ch/p/2.02.f', 'https://ahv-iv.ch/p/5.01.f', 'https://eak.admin.ch/eak/fr/home/EAK/publikationen/jahresberichte/jahresbericht-2023/beitraege.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/beitragspflicht.html', 'https://ahv-iv.ch/p/6.01.f', 'https://ahv-iv.ch/p/2.10.f']
--------------------_
Où sont inscrites les bonifications pour tâches d’assistance ?
https://www.ahv-iv.ch/p/1.04.f
['https://ahv-iv.ch/p/1.03.f', 'https://ahv-iv.ch/p/1.01.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/kontoauszug.html', 'https://ahv-iv.ch/p/3.06.f', 'https://ahv-iv.ch/p/4.13.f', 'https://ahv-iv.ch/p/1.07.f', 'https://ahv-iv.ch/p/4.02.f', 'https://ahv-iv.ch/p/4.03.f', 'https://ahv-iv.ch/p/4.04.f', 'https://ahv-iv.ch/p/4.16.f']
--------------------_
Où sont inscrites les bonifications pour tâches éducatives ?
https://www.ahv-iv.ch/p/1.04.f
['https://ahv-iv.ch/p/1.03.f', 'https://ahv-iv.ch/p/1.07.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/kontoauszug.html', 'https://ahv-iv.ch/p/1.01.f', 'https://ahv-iv.ch/p/4.04.f', 'https://ahv-iv.ch/p/4.02.f', 'https://ahv-iv.ch/p/6.01.f', 'https://eak.admin.ch/eak/fr/home/Firmen/erwerbsersatz/militaer_jugend_und_sport.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/steuerausweis.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/arbeitsunterbruch_keine_erwerbstaetigkeit/militaer_jugend_und_sport.html']
--------------------_
Quel est le montant du revenu minimal ?
https://www.ahv-iv.ch/p/1.04.f
['https://ahv-iv.ch/p/2.04.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/arbeit/teilzeitbeschaeftigung.html', 'https://eak.admin.ch/eak/fr/home/EAK/publikationen/mitteilungs-archiv/die-ahv-wir-dieses-jahr-75-jahre-alt.html', 'https://eak.admin.ch/eak/fr/home/Firmen/familienzulagen/meldepflicht/familienzulagen.html', 'https://ahv-iv.ch/p/6.09.f', 'https://ahv-iv.ch/p/2.03.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/kinder/familienzulagen.html', 'https://eak.admin.ch/eak/fr/home/Firmen/beitraege_und_loehne/akontobeitraege.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/reform-ahv21/kuerzungssaetze-bei-vorbezug.html', 'https://ahv-iv.ch/p/6.01.f']
--------------------_
Les cotisations peuvent-elles être payées ou exigées rétroactivement ?
https://www.ahv-iv.ch/p/1.04.f
['https://ahv-iv.ch/p/2.04.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/neuberechnung-der-altersrente-nach-dem-referenzalter.html', 'https://eak.admin.ch/eak/fr/home/Firmen/beitraege_und_loehne/lohnnachtraege_und_rueckerstattungen.html', 'https://ahv-iv.ch/p/3.08.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/vorbezug_aufschub/vorbezug.html', 'https://ahv-iv.ch/p/3.05.f', 'https://ahv-iv.ch/p/52.f', 'https://ahv-iv.ch/p/2.06.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/beitragspflicht.html', 'https://ahv-iv.ch/p/3.04.f']
--------------------_
Puis-je exiger une rectification des inscriptions ?
https://www.ahv-iv.ch/p/1.04.f
['https://ahv-iv.ch/p/1.01.f', 'https://eak.admin.ch/eak/fr/home/Firmen/Personal/versicherungsausweis.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/versicherungsausweis.html', 'https://eak.admin.ch/eak/fr/home/Firmen/Anschluss/zweigniederlassungen.html', 'https://eak.admin.ch/eak/fr/home/Firmen/erwerbsersatz/militaer_jugend_und_sport.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand/heirat_eingetragene_partnerschaft.html', 'https://ahv-iv.ch/p/4.15.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/neuberechnung-der-altersrente-nach-dem-referenzalter.html', 'https://eak.admin.ch/eak/fr/home/Firmen/familienzulagen/meldepflicht/familienzulagen.html']
--------------------_
Comment puis-je avoir connaissance des modifications ?
https://www.ahv-iv.ch/p/1.05.f
['https://ahv-iv.ch/p/31.f', 'https://eak.admin.ch/eak/fr/home/Firmen/familienzulagen/meldepflicht.html', 'https://eak.admin.ch/eak/fr/home/Firmen/Anschluss/zweigniederlassungen.html', 'https://eak.admin.ch/eak/fr/home/EAK/publikationen/neuerungen-2024.html', 'https://ahv-iv.ch/p/52.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand.html', 'https://eak.admin.ch/eak/fr/home/Firmen/familienzulagen/meldepflicht/melde--und-mitwirkungspflicht-gegenueber-der-familienausgleichsk.html', 'https://www.eak.admin.ch/eak/de/home/dokumentation/zivilstand.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/reform-ahv21/arbeiten-nach-65.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand/heirat_eingetragene_partnerschaft.html']
--------------------_
Qu’en est-il si je n’ai pas exercé d’activité lucrative pendant le mariage ?
https://www.ahv-iv.ch/p/1.05.f
['https://eak.admin.ch/eak/fr/home/dokumentation/arbeitsunterbruch_keine_erwerbstaetigkeit/keine_erwerbstaetigkeit.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/im_ausland/nichterwerbstaetige-im-ausland.html', 'https://ahv-iv.ch/p/2.03.f', 'https://ahv-iv.ch/p/3.03.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand/trennung_scheidung.html', 'https://ahv-iv.ch/p/2.10.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/beitragspflicht.html', 'https://ahv-iv.ch/p/4.04.f', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand/verwitwung.html', 'https://ahv-iv.ch/p/3.06.f']
--------------------_
Puis-je exiger une rectification des inscriptions?
https://www.ahv-iv.ch/p/1.05.f
['https://ahv-iv.ch/p/1.01.f', 'https://eak.admin.ch/eak/fr/home/Firmen/Personal/versicherungsausweis.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/versicherungsausweis.html', 'https://eak.admin.ch/eak/fr/home/Firmen/Anschluss/zweigniederlassungen.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand.html', 'https://eak.admin.ch/eak/fr/home/Firmen/erwerbsersatz/militaer_jugend_und_sport.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/pensionierung/neuberechnung-der-altersrente-nach-dem-referenzalter.html', 'https://eak.admin.ch/eak/fr/home/dokumentation/zivilstand/heirat_eingetragene_partnerschaft.html', 'https://ahv-iv.ch/p/4.15.f', 'https://eak.admin.ch/eak/fr/home/EAK/kontakt.html']
--------------------_

In [54]:
bad_retrieval = [doc for doc, b in zip(docs, recall) if not b]

bad_docs = []
for doc_list in bad_retrieval:
    retrieved_docs = []
    for doc in doc_list:
        retrieved_docs.append(doc["id"])
    bad_docs.append(retrieved_docs)

bad_docs

[[428, 426, 427, 449, 429, 425, 301, 431, 468, 278],
 [301, 423, 419, 263, 420, 372, 352, 305, 348, 458],
 [426, 301, 419, 320, 425, 458, 372, 334, 463, 433],
 [421, 419, 301, 441, 454, 424, 444, 445, 446, 457],
 [421, 424, 301, 419, 446, 444, 463, 294, 348, 322],
 [427, 314, 380, 280, 469, 426, 309, 271, 340, 463],
 [427, 329, 274, 443, 331, 440, 461, 429, 334, 439],
 [419, 263, 302, 257, 294, 303, 305, 456, 329, 280],
 [436, 279, 257, 383, 461, 303, 281, 133, 342, 305],
 [320, 346, 426, 438, 306, 433, 334, 446, 307, 441],
 [419, 263, 302, 257, 303, 294, 329, 305, 456, 391]]

In [70]:
bad_doc = db.query(Document).filter(Document.id == 428).first()
print(bad_doc.url)
print(bad_doc.text)

https://ahv-iv.ch/p/2.05.f
2.05 Cotisations
Rémunérations versées
lors de la cessation des
rapports de travail Etat au 1er janvier 20242En bref
En principe, toute rémunération d’une activité dépendante est réputée «salaire déterminant» pour le calcul des cotisations. Font également partie du salaire déterminant les rétributions versées, lors d’une cessation com -
plète des rapports de travail, par l’employeur ou par une institution qui lui est liée.
Voici quelques exemples de rémunérations versées lors de la cessation des rapports de travail qui font partie du salaire déterminant :
• arriérés de salaire,
• commissions,
• indemnités de vacances,
• gratifications,
• indemnités pour résiliation anticipée du contrat,
• prestations allouées en contrepartie du respect d’une clause de non-concurrence,
• versements effectués par l’employeur à bien plaire (hors prestations réglementaires) à titre de prévoyance en faveur de certains travailleurs.
Les éléments suivants, en revanche, ne sont pas soumis à cotisation :
• Prestations réglementaires de prévoyance Il s’agit des prestations d’institutions de prévoyance professionnelle auxquelles le bénéficiaire a droit au moment où l’événement assuré se produit.
• Montants versés à la caisse de pension Il s’agit de prestations sociales réglementaires accordées par l’em -
ployeur ; elles doivent être fournies sur la base d’un règlement.
A noter que si, après la cessation des rapports de travail, l’employeur conti -
nue de verser à la caisse de pension des cotisations d’un montant égal à celui payé jusqu’à ce moment-là, celles-ci font entièrement partie du salaire déterminant.
Le présent mémento informe les employeurs sur les rémunérations versées lors de la cessation des rapports de travail. 3Prestations sociales allouées lors de la cessation des rapports de travail
1 Quand les prestations sociales allouées sont-elles entièrement ou partiellement franches de cotisations ?
Les prestations sociales allouées sont partiellement ou entièrement franches de cotisations, à certaines conditions, lorsque la prévoyance profession -
nelle est insuffisante ou que l’employé a été licencié pour des impératifs d’exploitation. Ces prestations peuvent être versées lors de la cessation des rapports de travail sous forme de rente (par ex. rente-pont) ou de presta -
tions en capital (par ex. indemnité de départ). Les rentes sont converties en capital par la caisse de compensation. 4Prestations sociales allouées lorsque la prévoyance professionnelle est insuffisante
2 Quelles prestations ne sont pas prises en compte dans le salaire déterminant ?
Les prestations allouées, lors de la cessation de rapports de travail, pour toutes les années civiles complètes durant lesquelles l’employé n’avait pas de prévoyance professionnelle ne sont pas prises en compte dans le salaire déterminant tant qu’elles ne dépassent pas la moitié de la rente de vieil -
lesse mensuelle minimale au moment du versement.
3 Quelles prestations font partie du salaire déterminant ?
Le montant qui dépasse la moitié de la rente de vieillesse mensuelle minimale fait partie du salaire déterminant. Le montant du salaire perçu ne joue aucun rôle.
4 Exemple
Les rapports de travail d’une vendeuse de 54 ans engagée à temps partiel sont rompus après 15 ans de service en 2024. Elle obtient à bien plaire une indemnité unique en capital de 10 000 francs. N’ayant été soumise que partiellement à la LPP, elle n’a pas toujours payé des cotisations. Ainsi, elle n’était pas assurée du 1er août 2010 au 31 décembre 2014, ni du 1er avril 2019 au 31 juillet 2023. Il lui manque donc sept années entières de cotisations (4 + 3). L’art. 8bis RAVS est applicable.
Prestation en capital CHF 10 000.00
7 x 612.50 CHF (moitié de la rente mensuelle minimale) - CHF 4 287.50
Salaire déterminant CHF 5 712.505Prestations sociales allouées lors de licenciements pour des impératifs d’exploitation
5 Qu’entend-on par impératifs d’exploitation ?
Sont considérées comme des impératifs d’exploitation les fermetures d’entreprises, les fusions et les restructurations.
Il y a restructuration d’entreprise lorsque les conditions à remplir pour que l’institution de prévoyance assurant la prévoyance professionnelle obliga -
toire soit soumise à une liquidation partielle en vertu de l’art. 53b, al. 1, let. a ou b, LPP sont effectivement remplies ou lorsqu’il y a licenciement collectif avec plan social.
Les conditions à remplir pour qu’il y ait liquidation partielle sont prévues dans un règlement approuvé par l’autorité de surveillance LPP. Si les conditions d’une liquidation partielle de l’institution de prévoyance ne sont pas remplies malgré des licenciements, il y a tout de même res -
tructuration d’entreprise si les licenciements sont collectifs et réglés par un plan social.
Le plan social est une convention par laquelle l’employeur et les travailleurs (représentation des salariés ou syndicat) fixent les moyens d’éviter les licen -
ciements, d’en limiter le nombre ou d’en atténuer les conséquences (cf. art. 335h, al. 1, CO).
Est considéré comme licenciement collectif tout licenciement touchant une partie importante du personnel. Les prestations qui ne sont versées qu’à certains employés font partie du salaire déterminant.
6 Qu’en est-il des départs et des préretraites volontaires ?
Les dispositions d’exception ne s’appliquent pas lorsque les départs sont volontaires ou que les employés ont eux-mêmes choisi de partir plus tôt à la retraite, même en application d’un plan social ou d’un règlement de préretraite.67 Quelles prestations ne sont pas prises en compte dans le salaire déterminant ?
Les prestations allouées en cas de licenciement pour des impératifs d’exploitation ne font pas partie du salaire déterminant tant qu’elles ne dépassent pas quatre fois et demie de la rente de vieillesse annuelle maxi -
male.
8 Quelle part des prestations allouées sont prises en compte dans le salaire déterminant ?
En cas de licenciement pour des impératifs d’exploitation, la part des pres -
tations allouées qui dépasse quatre fois et demie de la rente de vieillesse annuelle maximale (132 300 francs en 2024) fait partie du salaire détermi -
nant. Le montant du salaire perçu ne joue aucun rôle.
Les prestations versées sous forme de rente doivent être converties en capital, pour déterminer leur valeur actuelle. La valeur actuelle d’une rente correspond au capital qui devrait être placé au taux d’intérêt technique à la date considérée pour pouvoir effectuer les versements futurs. La durée de vie probable est prise en compte. Un facteur est appliqué pour la conversion (voir tableaux ci-après). En cas d’année incomplète, le facteur temporaire est interpolé : on utilise la différence entre le facteur de l’âge supérieur et celui de l’âge inférieur.79 Facteurs de conversion
Extrait des facteurs de conversion en capital pour les types de rentes sui -
vants : Viagères, temporaires à l’âge de la retraite ou de référence et diffé -
rées jusqu’à l’âge de la retraite ou de référence :
Rente versée aux hommes Age en années viagèrestemporaires jusqu’à 65 ansdifférées jusqu’à à 65 ans
58 20,2 6,4 13,8
59 19,7 5,5 14,2
60 19,3 4,7 14,6
61 18,8 3,8 15,0
62 18,3 2,9 15,4
63 17,9 1,9 16,0
64 17,4 1,0 16,4
65 16,9 0,0 16,9
Rente versée aux femmes nées en 1960 ou avant Age en années viagèrestemporaires jusqu’à 64 ansdifférées jusqu’à à 64 ans
58 21,6 5,5 16,1
59 21,1 4,7 16,4
60 20,7 3,8 16,9
61 20,3 2,9 17,4
62 19,8 1,9 17,9
63 19,3 1,0 18,3
64 18,9 0,0 18,9
Rente versée aux femmes nées en 1964 ou après
Age en années viagèrestemporaires jusqu’à 65 ansdifférées jusqu’à à 65 ans
58 21,6 6,4 15,2
59 21,1 5,5 15,6
60 20,7 4,7 16,0
61 20,3 3,8 16,5
62 19,8 2,9 16,9
63 19,3 1,9 17,4
64 18,9 1,0 17,9
65 18,4 0,0 18,4
Formule de calcul : capital = rente annuelle x facteur rente annuelle = capital / facteur8L’âge est arrondi au mois entier inférieur et les facteurs sont déterminés par interpolation sur la base des facteurs applicables à l’âge supérieur et à l’âge inférieur.
Femmes nées en 1961, 1962 ou 1963
Les femmes nées en 1961, 1962 ou 1963 peuvent utiliser le calcu -
lateur en ligne pour la conversion des rentes en capital.
10 Exemple de facteur de conversion
Rente viagère pour un homme âgé de 62 ans et 3 mois.
62 ans, rente viagère Facteur 18,3
63 ans, rente viagère Facteur 17,9
62 ans et 3 mois Facteur 18,20
Facteur temporaire interpolé (18,3-17,9) x (9/12) + 17,9 = 18,20*
* (Facteur de l’âge inférieur – facteur de l’âge supérieur x (nombre de mois jusqu’au prochain anniversaire / 12) + facteur de l’âge supérieur)
Les tableaux complets fournissant les facteurs de conversion des rentes en capital sont disponibles dans la dirctive sur le salaire (DSD) sur le site de l’OFAS. Vous y trouverez aussi d’autres exemples.911 Exemple des rentes-ponts
La Brasserie Bierperle externalise son service de livraison à domicile en 2024 et doit de ce fait procéder à une restructuration. Sa caisse de pension est soumise à une liquidation partielle. Toutes les personnes travaillant au ser -
vice des transports sont concernées. Après plus de quinze ans de service, un agent de transport de 58 ans et 4 mois reçoit, en plus d’une rente de la prévoyance professionnelle obligatoire, une indemnité unique d’un mon -
tant de 150 000 francs, ainsi que des rentes-ponts annuelles de 82 000 francs (de 58 ans et 4 mois à 59 ans) et de 73 000 francs (de 60 à 65 ans). La rente pour retraite anticipée relève de l’art. 6, al. 2, let. h, RAVS et les autres prestations, de l’art. 8ter, al. 2, let. a, RAVS. Les rentes-ponts annuelles sont converties en capital.
Capital = rente mensuelle x 12 x facteur temporaire jusqu’à 65 ans x nombre de mois de perception de la rente / nombre de mois jusqu’à 65 ans. De 584/12 à 59 ans 82 000 francs Facteur temporaire interpolé jusqu’à 65 ans : (6,4 – 5,5) x (8/12) + 5,5 = 6,1 (82 000 x 6,1 x 20/80) CHF 125 050.–
De 60 à 65 ans 73 000 francs (73 000 x 6,1 x 60/80) CHF 333 975.–
Indemnité de départ CHF 150 000.–
Montant total CHF 609 025.–
Moins 4,5 fois la rente de vieillesse annuelle maximale en 2024 - CHF 132 300.–
Salaire déterminant CHF 476 725.–
La conversion des rentes en capital est effectuée par les caisses de com -
pensation. 10Dispositions communes
12 Et si l’activité est seulement réduite ?
Si l’activité est poursuivie à temps partiel, l’indemnité versée est intégrale -
ment soumise à cotisation. Seules des prestations de l’employeur, en cas de cessation complète des rapports de travail, peuvent être exemptées de l’obligation de cotiser.
13 L’âge et l’ancienneté jouent-ils un rôle ?
Non. L’âge et l’ancienneté n’ont aucune influence sur le calcul. Cela dit, la franchise accordée aux rentiers actifs ne s’applique pas.
14 Quand les cotisations doivent-elles être versées ?
Les cotisations sont dues au moment du versement de l’indemnité de départ. Si l’indemnité est versée sous forme de rentes, les cotisations sont dues au moment du premier versement. 11Renseignements et autres informations122.05-24/01-FCe mémento ne fournit qu’un aperçu général. Pour le règlement des cas individuels, seules les dispositions légales font foi. Les caisses de compensation et leurs agences fournissent volontiers tous les rensei -
gnements utiles. Vous trouverez la liste complète des caisses de com -
pensation sur le site www.avs-ai.ch .
Publié par le Centre d’information AVS/AI en collaboration avec l’Office fédéral des assurances sociales.
Edition novembre 2023. Toute reproduction, même partielle, n’est autorisée qu’avec l’accord écrit du Centre d’information AVS/AI. Ce mémento peut être obtenu auprès des caisses de compensation et de leurs agences ainsi qu’auprès des offices AI. Numéro de commande 2.05/f. Il est également disponible sous www.avs-ai.ch . Plus d’informations, de publications et de vidéos explicatives.

In [71]:
import numpy as np

def dcg(relevance_scores):
    """
    Compute Discounted Cumulative Gain (DCG)
    """
    return sum([rel / np.log2(idx + 2) for idx, rel in enumerate(relevance_scores)])

def ndcg(predicted_ranking, gold_standard_string):
    """
    Compute normalized Discounted Cumulative Gain (nDCG)
    
    :param predicted_ranking: List of strings in predicted order
    :param gold_standard_string: The gold standard string that should ideally be at position 1
    :return: nDCG score
    """
    # Calculate relevance scores for the predicted ranking
    relevance_scores = [1 if s == gold_standard_string else 0 for s in predicted_ranking]
    
    # Calculate the DCG for the predicted ranking
    dcg_score = dcg(relevance_scores)
    
    # Calculate the ideal DCG (when the gold standard string is at the top)
    ideal_ranking = [1] + [0] * (len(predicted_ranking) - 1)
    ideal_dcg = dcg(ideal_ranking)
    
    # Calculate nDCG
    ndcg_score = dcg_score / ideal_dcg if ideal_dcg > 0 else 0
    return ndcg_score

# Example usage
predicted_ranking = ["doc2", "doc3", "doc1", "doc4"]
gold_standard_string = "doc1"

ndcg_score = ndcg(predicted_ranking, gold_standard_string)
print(f"nDCG score: {ndcg_score:.4f}")

nDCG score: 0.5000

In [89]:
ranks = [d["url"].replace("www.", "") for d in docs[0]]
gold = eval_data.loc[0].url.replace("www.", "")

ndcg(ranks, gold)

1.0

In [90]:
ranks

['https://ahv-iv.ch/p/1.01.f',
 'https://eak.admin.ch/eak/fr/home/EAK/publikationen/jahresberichte/jahresbericht-2023/beitraege.html',
 'https://ahv-iv.ch/p/1.01.d',
 'https://ahv-iv.ch/p/1.04.f',
 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/kontoauszug.html',
 'https://ahv-iv.ch/p/1.05.f',
 'https://eak.admin.ch/eak/fr/home/EAK/portrait.html',
 'https://eak.admin.ch/eak/fr/home/EAK/organisation/zentraleausgleichsstelleZAS.html',
 'https://eak.admin.ch/eak/fr/home/EAK/unsere-leistungen/iv.html',
 'https://eak.admin.ch/eak/fr/home/Firmen/Anschluss.html']

In [91]:
gold

'https://ahv-iv.ch/p/1.01.f'

In [92]:
ranks[0] = "hhh"
ranks[3] = 'https://ahv-iv.ch/p/1.01.f'

In [93]:
ranks

['hhh',
 'https://eak.admin.ch/eak/fr/home/EAK/publikationen/jahresberichte/jahresbericht-2023/beitraege.html',
 'https://ahv-iv.ch/p/1.01.d',
 'https://ahv-iv.ch/p/1.01.f',
 'https://eak.admin.ch/eak/fr/home/dokumentation/mein_ahv-konto/kontoauszug.html',
 'https://ahv-iv.ch/p/1.05.f',
 'https://eak.admin.ch/eak/fr/home/EAK/portrait.html',
 'https://eak.admin.ch/eak/fr/home/EAK/organisation/zentraleausgleichsstelleZAS.html',
 'https://eak.admin.ch/eak/fr/home/EAK/unsere-leistungen/iv.html',
 'https://eak.admin.ch/eak/fr/home/Firmen/Anschluss.html']

In [94]:
ndcg(ranks, gold)

0.43067655807339306